package at.siemens.ct.jmz.executor;

import java.io.IOException;

public interface IExecutor {

  /**
   * Starts the process as configured and lets it read the model from a file generated by the model writer.
   */
  void startProcess() throws IOException;

  /**
   * Waits until the running process returns with a solution.
   * 
   * @return the time that has elapsed since {@link #startProcess()} (in milliseconds).
   */
  long waitForSolution() throws InterruptedException;

  /**
   * @return the output generated during the last solver run.
   */
  String getLastSolverOutput();

  /**
   * @return the error messages generated during the last solver run.
   */
  String getLastSolverErrors();

}