package at.siemens.ct.jmz.executor;

import java.io.IOException;

import at.siemens.ct.jmz.elements.IntVar;

public interface IExecutor {

  /**
   * @return the path of the MiniZinc executable.
   */
  String getPathToExecutable();

  /**
   * Changes the path of the MiniZinc executable.
   * 
   * @param pathToExecutable
   */
  void setPathToExecutable(String pathToExecutable);

  /**
   * Starts the process as configured and lets it read the model from a file generated by the model writer.
   */
  Process startProcess() throws IOException;

  /**
   * Waits until the running process returns with a solution.
   */
  void waitForSolution();

  /**
   * @return the value that has been assigned to the given variable in the current solution.
   */
  int getSolution(IntVar i);

  /**
   * @return the output generated during the last solver run.
   */
  String getLastSolverOutput();

  /**
   * @return the error messages generated during the last solver run.
   */
  String getLastSolverErrors();

  void setShowModelInIDE(boolean showModelInIDE);

}